version: '3.9'
services:
  app:
    build: .
    container_name: dc-products
    restart: always
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: dc-products-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
